---
- name: Deploy to K8s Cluster
  hosts: webservers   
  tasks:
    - name: clone repository
      git: >
        repo=https://github.com/arulhub/kub-dep-auth.git          
        dest=/opt/kub-demo/kub-dep-auth
    - name: Deploy Auth API
      shell: |
        kubectl apply -f=/opt/kub-demo/kub-dep-auth/auth.yaml